#!/usr/bin/env bash
#
# dev.sh — local development launcher for the toodaloo Expo app.
#
# Brings up an ISOLATED local Supabase stack (Docker via Colima), points the app
# at it through .env.development.local (which Expo loads at higher precedence than
# .env, so your prod .env is never touched), boots an iOS simulator, and builds/
# runs the Expo dev client.
#
# Usage:  ./scripts/dev.sh <command>
#
#   up          preflight -> db:up -> sim -> build-if-needed -> start  (the everyday command)
#   doctor      full static gate: toolchain + expo-doctor + SDK version check
#   smoke       runtime gate: drive login -> map and assert seeded data renders (Maestro)
#   db:up       ensure Docker + local Supabase are running; write local creds to env
#   db:reset    re-apply migrations 0001-0003 + seed.sql to the local DB
#   db:types    regenerate types/database.ts from the local schema
#   db:psql     open a psql shell on the local database
#   db:down     stop the local Supabase stack
#   sim         boot the target iOS simulator
#   ios         build + install + launch the dev client (first run, or after native changes)
#   start       start Metro for an already-installed dev client (fast path)
#   down        stop Metro helpers + the local Supabase stack
#
# Target simulator is "iPhone 17 Pro" by default; override with TOODALOO_SIM.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLIENT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$CLIENT_DIR"

BUNDLE_ID="com.jchau.toodaloo"
DEFAULT_SIM="${TOODALOO_SIM:-iPhone 17 Pro}"
ENV_LOCAL="$CLIENT_DIR/.env.development.local"
DB_URL="postgresql://postgres:postgres@127.0.0.1:54322/postgres"

log()  { printf '\033[1;36m▸ %s\033[0m\n' "$*"; }
ok()   { printf '\033[1;32m✓ %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m! %s\033[0m\n' "$*"; }
err()  { printf '\033[1;31m✗ %s\033[0m\n' "$*" >&2; }

# --- Docker / Colima ---------------------------------------------------------

ensure_docker() {
  if docker info >/dev/null 2>&1; then return 0; fi
  if command -v colima >/dev/null 2>&1; then
    log "Docker daemon not responding — starting Colima (4 CPU / 6 GB)…"
    colima start --cpu 4 --memory 6 --mount-type sshfs
  fi
  if docker info >/dev/null 2>&1; then return 0; fi
  err "Docker is not available. Start Colima ('colima start') or Docker Desktop, then retry."
  return 1
}

# --- Supabase ----------------------------------------------------------------

write_env_local() {
  local status_env API_URL ANON_KEY
  status_env="$(supabase status -o env 2>/dev/null)"
  API_URL="$(printf '%s\n' "$status_env" | sed -n 's/^API_URL="\(.*\)"$/\1/p')"
  ANON_KEY="$(printf '%s\n' "$status_env" | sed -n 's/^ANON_KEY="\(.*\)"$/\1/p')"
  if [[ -z "$API_URL" || -z "$ANON_KEY" ]]; then
    err "Could not read local Supabase credentials from 'supabase status'."
    return 1
  fi
  cat > "$ENV_LOCAL" <<EOF
# AUTO-GENERATED by scripts/dev.sh — local Supabase stack credentials.
# Expo loads .env.development.local ahead of .env in development, so these
# override the remote values without editing .env. DO NOT COMMIT this file.
# Regenerate: ./scripts/dev.sh db:up
# Fall back to remote (.env): delete this file, then restart Metro with -c.
EXPO_PUBLIC_SUPABASE_URL=$API_URL
EXPO_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY
EOF
  ok "App env → local Supabase ($API_URL)"
}

db_up() {
  ensure_docker || return 1
  if supabase status >/dev/null 2>&1; then
    log "Local Supabase already running."
  else
    log "Starting local Supabase stack…"
    supabase start >/dev/null
  fi
  write_env_local
  log "Inbucket (OTP emails): http://127.0.0.1:54324"
}

db_reset() {
  ensure_docker || return 1
  log "Resetting local DB (migrations 0001-0003 + seed.sql)…"
  supabase db reset
  ok "Local DB reset."
}

db_types() {
  ensure_docker || return 1
  log "Generating types/database.ts from local schema…"
  supabase gen types typescript --db-url "$DB_URL" > "$CLIENT_DIR/types/database.ts"
  ok "types/database.ts updated."
}

db_psql() {
  ensure_docker || return 1
  if command -v psql >/dev/null 2>&1; then
    exec psql "$DB_URL"
  else
    exec docker exec -it "$(docker ps --filter name=supabase_db --format '{{.Names}}' | head -1)" psql -U postgres
  fi
}

db_down() {
  log "Stopping local Supabase stack…"
  supabase stop || true
  ok "Local Supabase stopped."
}

# --- iOS simulator + Expo ----------------------------------------------------

sim_udid() {
  xcrun simctl list devices available \
    | grep -F "$DEFAULT_SIM (" | head -1 \
    | grep -oE '[0-9A-Fa-f-]{36}' | head -1
}

sim() {
  local udid; udid="$(sim_udid)"
  if [[ -z "$udid" ]]; then
    err "Simulator \"$DEFAULT_SIM\" not found. Set TOODALOO_SIM to an available device:"
    xcrun simctl list devices available | grep -iE "iphone" >&2
    return 1
  fi
  log "Booting simulator: $DEFAULT_SIM"
  xcrun simctl boot "$udid" 2>/dev/null || true
  open -a Simulator
  ok "Simulator ready."
}

app_installed() {
  xcrun simctl get_app_container booted "$BUNDLE_ID" app >/dev/null 2>&1
}

build_ios() {
  log "Building & installing the dev client (first run compiles native + pods — slow)…"
  npx expo run:ios --device "$DEFAULT_SIM"
}

start() {
  log "Starting Metro (dev client, cache cleared so new env inlines)…"
  npx expo start --dev-client -c
}

# --- Orchestration -----------------------------------------------------------

up() {
  preflight
  db_up
  sim
  if app_installed; then
    log "Dev client already installed on the simulator."
    start
  else
    build_ios
  fi
}

down() {
  db_down
  ok "Down. (Metro, if running, can be stopped with Ctrl-C in its terminal.)"
}

# --- Smoke test (runtime gate) ----------------------------------------------
# Drives login -> authenticated map against the local stack and asserts the seeded
# bathrooms render. This is the gate that catches runtime rendering regressions
# (like the Reanimated crash) that jest and a green native build both miss.

metro_up() { curl -s -o /dev/null "http://localhost:8081/status" 2>/dev/null; }

ensure_metro() {
  metro_up && return 0
  log "Starting Metro in the background…"
  ( npx expo start --dev-client >/dev/null 2>&1 & )
  local i=0
  until metro_up || [[ $i -ge 60 ]]; do sleep 1; i=$((i+1)); done
  metro_up
}

resolve_maestro() {
  # Maestro needs JDK 11+, but the system default here is JDK 8 — point it at brew's openjdk@17.
  if command -v brew >/dev/null 2>&1; then
    local jh; jh="$(brew --prefix openjdk@17 2>/dev/null)"
    if [[ -n "$jh" ]]; then
      [[ -d "$jh/libexec/openjdk.jdk/Contents/Home" ]] && export JAVA_HOME="$jh/libexec/openjdk.jdk/Contents/Home" || export JAVA_HOME="$jh"
    fi
  fi
  export PATH="$HOME/.maestro/bin:$PATH"
  command -v maestro >/dev/null 2>&1
}

smoke() {
  ensure_docker || return 1
  supabase status >/dev/null 2>&1 || { log "Starting local Supabase…"; supabase start >/dev/null; }
  write_env_local >/dev/null
  sim
  if ! app_installed; then
    err "Dev client isn't installed on the simulator. Build it first:  ./scripts/dev.sh ios"
    return 1
  fi
  ensure_metro || { err "Metro isn't reachable on :8081."; return 1; }
  log "Pointing the simulator's GPS at the seeded NYC data…"
  xcrun simctl location booted set 40.7580,-73.9855 || true
  # Pre-grant location so fresh installs don't stall on the permission prompt
  # (the flow also taps it optionally, as a fallback).
  xcrun simctl privacy booted grant location-always "$BUNDLE_ID" 2>/dev/null || true
  if ! resolve_maestro; then
    err "Maestro not installed. One-time setup (openjdk@17 is already present):"
    err "  curl -Ls https://get.maestro.mobile.dev | bash"
    return 1
  fi
  local SR; SR="$(supabase status -o env 2>/dev/null | sed -n 's/^SERVICE_ROLE_KEY="\(.*\)"$/\1/p')"
  log "Running Maestro login→data smoke (JAVA_HOME=$JAVA_HOME)…"
  maestro test -e SERVICE_ROLE="$SR" "$CLIENT_DIR/.maestro/login-smoke.yaml"
}

preflight() {
  local missing=0
  _check() { # label  test-cmd  hint
    if eval "$2" >/dev/null 2>&1; then ok "$1"; else warn "$1 — $3"; missing=1; fi
  }
  log "Toolchain check"
  _check "Node"          "command -v node"           "install Node 20+"
  _check "Xcode"         "xcodebuild -version"        "install Xcode from the App Store"
  _check "CocoaPods"     "command -v pod"             "sudo gem install cocoapods (or brew install cocoapods)"
  _check "Supabase CLI"  "command -v supabase"        "brew install supabase/tap/supabase"
  _check "Docker CLI"    "command -v docker"          "brew install docker && brew install colima"
  _check "Docker daemon" "docker info"                "run 'colima start' (or start Docker Desktop)"
  _check "Base .env"     "test -f $CLIENT_DIR/.env"   "copy .env.example to .env and fill in keys"
  _check "Simulator '$DEFAULT_SIM'" "test -n \"\$(sim_udid)\"" "set TOODALOO_SIM to an installed device"
  if [[ "$missing" -ne 0 ]]; then
    warn "Some checks failed — resolve the hints above. 'up' will still try where it can."
  else
    ok "All toolchain checks passed."
  fi
  return 0
}

# Full static gate: toolchain + Expo dependency/config health. Catches the dep rot
# and version drift that silently broke the build here (unused/duplicate native
# modules, packages off the SDK's pinned set, config-plugin problems). Slower than
# `preflight` (which is what `up` runs), so invoke it explicitly or in CI.
doctor() {
  preflight
  log "Dependency & config health (expo-doctor)…"
  npx expo-doctor || warn "expo-doctor found issues (above) — worth fixing."
  log "SDK version alignment (expo install --check)…"
  npx expo install --check || warn "Some packages drift from the SDK's expected versions."
}

# --- Dispatch ----------------------------------------------------------------

case "${1:-up}" in
  up)        up ;;
  doctor)    doctor ;;
  db:up)     db_up ;;
  db:reset)  db_reset ;;
  db:types)  db_types ;;
  db:psql)   db_psql ;;
  db:down)   db_down ;;
  sim)       sim ;;
  ios)       build_ios ;;
  start)     start ;;
  smoke)     smoke ;;
  down)      down ;;
  *)
    err "Unknown command: $1"
    sed -n '2,40p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
    exit 1 ;;
esac
